---
title: "0430_Should_relationship_11_items"
author: "Chun Hsien Wu"
date: "2022年4月30日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### 應有之情 PCM model analysis
```{r}
rm(list=ls())
setwd("/home/son/RepTemplates/paper_du")
library("TAM")

dat_item <- read.csv("item49-64.csv") 

# distract polytomous data from dat
dat_item <- dat_item[, 11: 21]
dat_item <- na.omit(dat_item)

dat_item <- dat_item - 1
dim(dat_item)
```
```{r,attr.output='style="max-height: 100px;"'}
# change colnames fromQ54 to Q64, change it to item_1, item_2, ..., item_11
names(dat_item)[1] <- "6"
names(dat_item)[2] <- "7"
names(dat_item)[3] <- "8"
names(dat_item)[4] <- "9"
names(dat_item)[5] <- "10"
names(dat_item)[6] <- "11"
names(dat_item)[7] <- "12"
names(dat_item)[8] <- "13"
names(dat_item)[9] <- "14"
names(dat_item)[10] <- "15"
names(dat_item)[11] <- "16"

mod1 <- tam(dat_item)

#Item parameters
mod1$xsi

#  Plot and look at difficulties/thresholds
plot(mod1,type = "items")
```

```{r}
tthresh <- tam.threshold(mod1)

tthresh

par(ps=9)
dotchart(t(tthresh), pch=19)

library("WrightMap")
Ability = tam.wle(mod1)

wrightMap(Ability$theta, tthresh)

fit2 <- msq.itemfit(mod1)
summary(fit2)
```

