---
title: "should_relationship about teacher and students"
author: "Chun Hsien Wu"
date: "2021年12月17日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
# 08.12.2021
# Partial Credit Model for teacher and students' relationship item analysis
# # 應有之情 
#Q54(雙接) Q56(起答) Q57(報師) Q59(師呼) Q60(信師) Q61(誠答) Q62(克尊) Q63(洗恭) Q64(舉發) 共9題
# True relationship item_49 - item_53
rm(list=ls())
setwd("/home/son/RepTemplates/paper_du")
```
```{r}
# load TAM package
#Run IRT analysis for partial credit model (MML estimation)
library("TAM")
# reading and writing CSV files into R
 dat <- read.csv("items.csv") 
```


```{r,attr.output='style="max-height: 100px;"'}
# get names of colnames and rownames
colnames(dat)

# all the response value - 1
dat1 <- dat -1

# delete NA rows, now, we get clean data, the dimension of dat2 is 970*16
dat2 <- na.omit(dat1)
dim(dat2)

## because Q55 and Q58 should be deleted
## now we got 14 items, 
# Q54(雙接) Q56(起答) Q57(報師) Q59(師呼) Q60(信師) Q61(誠答) Q62(克尊) Q63(洗恭) Q64(舉發) 共9題
s_dat <- dat2[,-c(1:5)]
```

```{r,attr.output='style="max-height: 100px;"'}
#Run IRT analysis for partial credit model (MML estimation)
mod1 <- tam(s_dat)
#Item parameters
mod1$xsi
```
```{r,attr.output='style="max-height: 100px;"'}
#Thurstonian thresholds
tthresh <- tam.threshold(mod1)
tthresh
```
```{r,attr.output='style="max-height: 100px;"'}
#Plot Thurstonian thresholds
par(ps=9)
dotchart(t(tthresh), pch=19)
# to get the wrighMap plot
library("WrightMap")
Ability = tam.wle(mod1)

wrightMap(Ability$theta, tthresh)
```
```{r}
#Plot expected scores curves
plot(mod1)

```
```{r, attr.output='style="max-height: 100px;"'}
##
# TAM fit statistics
fit1 <- TAM::tam.fit( mod1 )

## below from page 151 
## Applying the Rasch model in social sciences using R
fit2 <- msq.itemfit(mod1)
fit2
```

