---
title: "華人師生關係量表之試題分析：部份給分模式之應用"
author: "Chun Hsien Wu"
date: "2022年2月22日"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
華人師生關係量表之試題分析：部份給分模式之應用


中文摘要

關鍵詞

正文
壹(頓號)緒論(置中)

在人口少子化以及強調民主 個人自由的思潮的影響下 師生間的關係已經從傳統上 尊師重道的倫理觀念轉換為權利與義務的對等關係（特別是在教師法第十四條第一項第八款所稱「教學不力或不能勝任工作」情事認定參考基準) 
	校園中 師生間關係的好壞不但影響學生的學習態度與學習成效 更有可能影響間接或直接影響親師之間的溝通
	
	過去有關師生關係研究有從社會學中角色理論觀點出發( 分號 文獻)由學生知覺到教師的角色來分析師生間的關係(分號 文獻)也有從教師領導的類型來了解學生的學習行為或
	生活適應的關係(分號 文獻)從心理學角度進行師生間關係的研究從學生人格依附觀點出發來了解師生關係(引文獻) 
	(杜永泰有關動機觀點的論述 我覺得好像不用放進裡面)此外以提昇學生學習動機為目標導向的師生關係研究則是認為好的師生關係可以提昇學生的學習動機
 
	***1/24 Monday afternoon 我來進行杜永泰華人師生關係的敘述**
	**華人社會文化的關係分類系統**
	(以下完全引自杜永泰 拿到楊中芳書後 要改成自己論述的方式)楊中芳(2001)以人際情感的多寡來定義『關係』(杜永泰)
	
	杜永泰(2004)從社會文化觀點編製切入編製師生關係量表(符號) 在量表的理論依據上採取 (杜永泰)楊中芳(2001)以人際情感的多寡來定義「關係」
	認為華人人際交往最重要的成份是情感交流 將人際情感分為既定（頓號）義務性的「人情」和真有、自發性的「感情」，(杜永泰)將之套入
	校園中師生關係的成為就成為「感情表達行為」和「人情表達行為」（杜永泰）。杜永泰即以「感情表達行為」和「人情表達行為」雙層結構作為測量師生關係的向度。

	*論述過去研究中是否師生關係存在有性別上的差異(DIF)
	*論述過去研究中是否師生關係存有城鄉差距(DIF)
	
	
	敘述試題反應理論 Rasch模式的特色與優點(可參考王文中 巫博瀚)

	敘述 Partial Credit Model的內涵

	敘述檢測試題存有DIF可用的統計方法 以及本研究中使用的DIF方法

	DIMTEST
	(遭遇重大困難 原來我對 detect的原理 其實並不熟悉)

	polyDETECT(Zhang & Stout, 1999; Zhang, 2007)是DETECT多分題向度檢測的延伸運作的規則與detect程式幾乎一樣 
	PolyDETECT 程序有三個統計指標;分別是 D(P), ASSI(P)以及 R(P)指標
	D(P)指標表示基於(辨識)簡單向度結構下 測驗資料所能觀察到多向度的最大程度
	ASSI(P)和R(P)指標顯示測驗資料是否能呈現單純結構與否
	這個程序將試題做成p個分割至K個非重疊集群 在這些可能的叢集分割中尋找最大的 P值
	對於任何一個分割 D(P)指標定義為所有signed條件試題共變的平均值
	所有可能的分割都會加以檢驗 最大的D(P)值 表示最佳的試題分割
	DETECT指標為Zhang 及 Stout(1999)所定義
$$D(P)=\frac{2}{n(n-1)}\sum_{\substack{
1 \le  i_1 \le  i_2 < n
}} \delta_i{_1}_i{_2}(P)E[cov(X_i{_1},X_i{_2)}|\Theta_T]$$

P代表測驗中試題可能的分割群組
此處p是測驗試題的分割 當試題$i_1$ 和試題$i_2$屬於同一向度時 $\delta_i{_1}_i{_2}=1$
當試題i1 和試題i2分屬不同向度時 $\delta_i{_1}_i{_2} = -1$

當測驗為單一向度時 D(P)值會等於零 
D(P)值越大 表示該試題分割越是遠離單向度 
當PolyDETECT宣告測驗資料為多向度時 測驗試題分割的P組試題代表測驗潛在構念有P個向度

此外PolyDetect 還有兩個輔助指標 ASSI(P)和R(P)指標
ASSI(P)為 the approximate simple structure index,  
	(黃宏宇)McDonald與Mok(1995)提出兩種分析測驗向度的方法 
	第一個是完全訊息法(full information)的因素分析取向
	它的原理是控制影響作答反應能力的條件下 每一題答對機率會互相獨立
	完全分析法的因素分析取向又稱為局部獨立的強勢型(strong form)
	完全訊息的因素分析取向多採用非線性因素分析法進行 例如TESTFACT	

	第二種是雙變項訊息(bivariate information)的因素分析法
	它的原理是排除影響作答的能力向度後 配對的試題或殘差變異間不存在共變關係
	
	
		綜上所述 本研究有以下幾個主要目的
		1.檢驗華人師生關係量表中真有之情與應有之情屬於單向度或雙向度分析	
		2.檢驗華人師生關係量表是否因性別及學生所屬學校類別存在DIF試題
		3.分析華人師生關係量表模式-資料適配度
		4.以部份給分模式分析受試學生潛在能力特質的分布 了解試題與受試學生潛在特質的對應關係(這一段與黃宏宇太像 一定要修改)
	
	貳(頓號)研究方法(置中)
	
	一 研究工具
		本研究使用測量工具為師生關係量表(杜永泰 )為李特克氏五等第量表 選項類別由不同意 有點不同意 沒意見 有點同意 同意
		因師生關係量表在向度分析時為兩個分量表 其一為「感情表達行為」(共四題)「人情表達行為」(共九題)合計整份量表共十三題
	二樣本描述
		研究樣本來自桃園市十三個行政區 依班級數量為比例 以班級為叢集抽樣單位 分層隨機抽取二十所國民小學六年級學生進行
		問卷調查 得到男生共   人 女生共 人 合計970份有效問卷 樣本中來自勇類學校(全校班級數12班以下)共 人 來自仁類學校(13至24班)
		共 人 來自智類學校(全校班級數24班以上)共  人

	三資料分析與處理 (參考 黃宏宇)
		本研究採取單向度試題反應理論中部份給分模式進行試題分析
		以R軟體中 TAM package 進行量表試題分析 TAM package在試題難度參數及
		受試者能力參數估計上採用邊際最大概似估計法(marginal maximum likelihood, MML)
		進行參數估計
		向度偵測採那一個軟體 何種統計程序
		

		
	參(頓號)結果與討論(置中)

		一 單向度檢驗
			＠先做向度分析 分為兩個向度

		二部份給分模式分析結果
		＠也要分為兩個向度分別呈現	
		＠呈現 部份給分模式結果 包含 infit and outfit (參考 巫博瀚)

			?尋找如何呈現測驗訊息函數 TAM package
			？補上測驗訊息函數 並放上圖表（仿效 巫博瀚）

		三差異試題功能分析
		
		四潛在特質分佈檢驗
		＠ 呈現試題難度涵蓋性與潛在特質分佈檢驗(參考 黃宏宇)
		＠是否可以依照應有之情 及 真有之情試題特徵曲線來判斷 決定 華人師生關係量表 直接採用三等第量表取代五等第李克特量表
	結論與建議(置中)
	
	參考文獻(置中)
	附錄(非必要)  

